version: '3'

services:

  wst-mng:
    build: .
#    command: gunicorn EarthlytixCloud.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
          - postgres
  postgres:
    image: postgres
    ports:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: form
#  nginx:
#    build: ./nginx
#    restart: always
#    ports:
#      - "1337:80"
#    depends_on:
#        - wst-mng
volumes:
  db: